Search.appendIndex(
    [
                {
            "fqsen": "\\Finance\\IA\\Account",
            "name": "Account",
            "summary": "This\u0020is\u0020the\u0020main\u0020class\u0020that\u0020provides\u0020all\u0020the\u0020functionality\u0020needed\u0020to\u0020manipulate\u0020a\u0020Finance\u0020Interest\u0020Account.",
            "url": "classes/Finance-IA-Account.html"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AgetUuid\u0028\u0029",
            "name": "getUuid",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_getUuid"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AsetUuid\u0028\u0029",
            "name": "setUuid",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_setUuid"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AcreateInterestAccount\u0028\u0029",
            "name": "createInterestAccount",
            "summary": "Not\u0020currently\u0020supported\u0020or\u0020offered.",
            "url": "classes/Finance-IA-Account.html#method_createInterestAccount"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AsetUserStats\u0028\u0029",
            "name": "setUserStats",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_setUserStats"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AgetFinanceApiRequest\u0028\u0029",
            "name": "getFinanceApiRequest",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_getFinanceApiRequest"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AgetUserStats\u0028\u0029",
            "name": "getUserStats",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_getUserStats"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AopenInterestAccount\u0028\u0029",
            "name": "openInterestAccount",
            "summary": "Open\u0020and\u0020activated\u0020a\u0020Finance\u0020Interest\u0020Account.",
            "url": "classes/Finance-IA-Account.html#method_openInterestAccount"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AlistStatement\u0028\u0029",
            "name": "listStatement",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#method_listStatement"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003AdepositFunds\u0028\u0029",
            "name": "depositFunds",
            "summary": "Deposit\u0020funds\u0020into\u0020the\u0020account",
            "url": "classes/Finance-IA-Account.html#method_depositFunds"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003Apayout\u0028\u0029",
            "name": "payout",
            "summary": "Calculate\u0020how\u0020much\u0020needs\u0020to\u0020be\u0020paid\u0020out\u0020in\u0020interest\u0020rate,\u0020including\u0020previously\u0020skipped\u0020values.",
            "url": "classes/Finance-IA-Account.html#method_payout"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003A\u0024userStats",
            "name": "userStats",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#property_userStats"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003A\u0024uuid",
            "name": "uuid",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#property_uuid"
        },                {
            "fqsen": "\\Finance\\IA\\Account\u003A\u003A\u0024interestAccountProcessor",
            "name": "interestAccountProcessor",
            "summary": "",
            "url": "classes/Finance-IA-Account.html#property_interestAccountProcessor"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes",
            "name": "ErrorCodes",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes\u003A\u003ANONE",
            "name": "NONE",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html#constant_NONE"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html#constant_DEFAULT"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes\u003A\u003AACCOUNT_NOT_SET",
            "name": "ACCOUNT_NOT_SET",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html#constant_ACCOUNT_NOT_SET"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes\u003A\u003AINTEREST_ASSIGN",
            "name": "INTEREST_ASSIGN",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html#constant_INTEREST_ASSIGN"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\ErrorCodes\u003A\u003ADEPOSIT_INVALID",
            "name": "DEPOSIT_INVALID",
            "summary": "",
            "url": "classes/Finance-IA-Config-ErrorCodes.html#constant_DEPOSIT_INVALID"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestIntervalConfig",
            "name": "InterestIntervalConfig",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestIntervalConfig.html"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestIntervalConfig\u003A\u003APAYOUT_INTERVAL_DAYS",
            "name": "PAYOUT_INTERVAL_DAYS",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestIntervalConfig.html#constant_PAYOUT_INTERVAL_DAYS"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestRatesConfig",
            "name": "InterestRatesConfig",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestRatesConfig.html"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestRatesConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestRatesConfig.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestRatesConfig\u003A\u003AsetRates\u0028\u0029",
            "name": "setRates",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestRatesConfig.html#method_setRates"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestRatesConfig\u003A\u003AgetRates\u0028\u0029",
            "name": "getRates",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestRatesConfig.html#method_getRates"
        },                {
            "fqsen": "\\Finance\\IA\\Config\\InterestRatesConfig\u003A\u003A\u0024rates",
            "name": "rates",
            "summary": "",
            "url": "classes/Finance-IA-Config-InterestRatesConfig.html#property_rates"
        },                {
            "fqsen": "\\Finance\\IA\\Exception\\AccountException",
            "name": "AccountException",
            "summary": "",
            "url": "classes/Finance-IA-Exception-AccountException.html"
        },                {
            "fqsen": "\\Finance\\IA\\Exception\\AmountException",
            "name": "AmountException",
            "summary": "",
            "url": "classes/Finance-IA-Exception-AmountException.html"
        },                {
            "fqsen": "\\Finance\\IA\\Exception\\InterestException",
            "name": "InterestException",
            "summary": "",
            "url": "classes/Finance-IA-Exception-InterestException.html"
        },                {
            "fqsen": "\\Finance\\IA\\Exception\\UuidException",
            "name": "UuidException",
            "summary": "",
            "url": "classes/Finance-IA-Exception-UuidException.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\InterestRateObject",
            "name": "InterestRateObject",
            "summary": "",
            "url": "classes/Finance-IA-Object-InterestRateObject.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\InterestRateObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Object-InterestRateObject.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\InterestRateObject\u003A\u003A\u0024yearlyInterestRate",
            "name": "yearlyInterestRate",
            "summary": "",
            "url": "classes/Finance-IA-Object-InterestRateObject.html#property_yearlyInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\InterestRateObject\u003A\u003A\u0024minMonthlyIncome",
            "name": "minMonthlyIncome",
            "summary": "",
            "url": "classes/Finance-IA-Object-InterestRateObject.html#property_minMonthlyIncome"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\InterestRateObject\u003A\u003A\u0024maxMonthlyIncome",
            "name": "maxMonthlyIncome",
            "summary": "",
            "url": "classes/Finance-IA-Object-InterestRateObject.html#property_maxMonthlyIncome"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject",
            "name": "ResultObject",
            "summary": "A\u0020standardised\u0020messaging\u0020result\u0020object\u0020for\u0020easy\u0020manipulation\u0020and\u0020re\u002Duse",
            "url": "classes/Finance-IA-Object-ResultObject.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AsetResult\u0028\u0029",
            "name": "setResult",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_setResult"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AsetErrorCode\u0028\u0029",
            "name": "setErrorCode",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_setErrorCode"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AsetMessage\u0028\u0029",
            "name": "setMessage",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_setMessage"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AsetSuccess\u0028\u0029",
            "name": "setSuccess",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_setSuccess"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_setData"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AclearResult\u0028\u0029",
            "name": "clearResult",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_clearResult"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003AreturnResult\u0028\u0029",
            "name": "returnResult",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#method_returnResult"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_NONE",
            "name": "RESULT_NONE",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_NONE"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_INTEREST_ZERO",
            "name": "RESULT_INTEREST_ZERO",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_INTEREST_ZERO"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_INTEREST_FAILED",
            "name": "RESULT_INTEREST_FAILED",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_INTEREST_FAILED"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_PAYOUT_COUNT_FAILED",
            "name": "RESULT_PAYOUT_COUNT_FAILED",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_PAYOUT_COUNT_FAILED"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_ACCOUNT_IS_ACTIVATED",
            "name": "RESULT_ACCOUNT_IS_ACTIVATED",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_ACCOUNT_IS_ACTIVATED"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_ACCOUNT_NOT_ACTIVATED",
            "name": "RESULT_ACCOUNT_NOT_ACTIVATED",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_ACCOUNT_NOT_ACTIVATED"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_DEPOSIT_AMOUNT_MIN_LIMIT",
            "name": "RESULT_DEPOSIT_AMOUNT_MIN_LIMIT",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_DEPOSIT_AMOUNT_MIN_LIMIT"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_OPENED_AND_ACTIVE",
            "name": "RESULT_OPENED_AND_ACTIVE",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_OPENED_AND_ACTIVE"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003ARESULT_DEPOSIT_PAYOUT_LESS_MINIMUM",
            "name": "RESULT_DEPOSIT_PAYOUT_LESS_MINIMUM",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#constant_RESULT_DEPOSIT_PAYOUT_LESS_MINIMUM"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003A\u0024success",
            "name": "success",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#property_success"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003A\u0024errorCode",
            "name": "errorCode",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#property_errorCode"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#property_message"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\ResultObject\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Finance-IA-Object-ResultObject.html#property_data"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject",
            "name": "UserStatsObject",
            "summary": "User\u0020Stats\u0020as\u0020an\u0020object\u0020for\u0020easy\u0020re\u002Duse\u0020between\u0020classes\u0020and\u0020methods",
            "url": "classes/Finance-IA-Object-UserStatsObject.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetMonthlyIncome\u0028\u0029",
            "name": "getMonthlyIncome",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getMonthlyIncome"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetUuid\u0028\u0029",
            "name": "getUuid",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getUuid"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetStatement\u0028\u0029",
            "name": "getStatement",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getStatement"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetStatement\u0028\u0029",
            "name": "setStatement",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setStatement"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetInterestPayoutPending\u0028\u0029",
            "name": "getInterestPayoutPending",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getInterestPayoutPending"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetInterestPayoutPending\u0028\u0029",
            "name": "setInterestPayoutPending",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setInterestPayoutPending"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetInterestPayoutCompleted\u0028\u0029",
            "name": "getInterestPayoutCompleted",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getInterestPayoutCompleted"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetInterestPayoutCompleted\u0028\u0029",
            "name": "setInterestPayoutCompleted",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setInterestPayoutCompleted"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetInterestRate\u0028\u0029",
            "name": "getInterestRate",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetInterestRate\u0028\u0029",
            "name": "setInterestRate",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetTotalBalance\u0028\u0029",
            "name": "getTotalBalance",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getTotalBalance"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetTotalBalance\u0028\u0029",
            "name": "setTotalBalance",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setTotalBalance"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AsetLastPayoutDate\u0028\u0029",
            "name": "setLastPayoutDate",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_setLastPayoutDate"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AgetDaysFromLastPayout\u0028\u0029",
            "name": "getDaysFromLastPayout",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_getDaysFromLastPayout"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AisActive\u0028\u0029",
            "name": "isActive",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_isActive"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003AfetchData\u0028\u0029",
            "name": "fetchData",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#method_fetchData"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024active",
            "name": "active",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_active"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024uuid",
            "name": "uuid",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_uuid"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024monthly_income",
            "name": "monthly_income",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_monthly_income"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024interest_rate",
            "name": "interest_rate",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_interest_rate"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024statement",
            "name": "statement",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_statement"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024total_balance",
            "name": "total_balance",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_total_balance"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024interest_payout_completed",
            "name": "interest_payout_completed",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_interest_payout_completed"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024interest_payout_pending",
            "name": "interest_payout_pending",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_interest_payout_pending"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UserStatsObject\u003A\u003A\u0024last_payout_date",
            "name": "last_payout_date",
            "summary": "",
            "url": "classes/Finance-IA-Object-UserStatsObject.html#property_last_payout_date"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object",
            "name": "UUIDv4Object",
            "summary": "Basic\u0020object\u0020for\u0020user\u0020id\u0020based\u0020on\u0020UUID\u0020v4\u0020requirements",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html#method_isValid"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object\u003A\u003AsetUUID\u0028\u0029",
            "name": "setUUID",
            "summary": "",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html#method_setUUID"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object\u003A\u003AgetUUID\u0028\u0029",
            "name": "getUUID",
            "summary": "",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html#method_getUUID"
        },                {
            "fqsen": "\\Finance\\IA\\Object\\UUIDv4Object\u003A\u003A\u0024uuid",
            "name": "uuid",
            "summary": "",
            "url": "classes/Finance-IA-Object-UUIDv4Object.html#property_uuid"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor",
            "name": "InterestAccountProcessor",
            "summary": "A\u0020basic\u0020middle\u002Dservice\u0020interface\u0020to\u0020be\u0020used.\u0020Can\u0020be\u0020ommitted,\u0020but\u0020provides\u0020an\u0020easier\u0020way\u0020to\u0020mock\u0020for\u0020creation\u0020of\u0020unit\u0020tests",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003AsetChatApiRequest\u0028\u0029",
            "name": "setChatApiRequest",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#method_setChatApiRequest"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003AactivateAccount\u0028\u0029",
            "name": "activateAccount",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#method_activateAccount"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003AgetInterestRate\u0028\u0029",
            "name": "getInterestRate",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#method_getInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003AgetFinanceApiRequest\u0028\u0029",
            "name": "getFinanceApiRequest",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#method_getFinanceApiRequest"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestAccountProcessor\u003A\u003A\u0024financeApiRequest",
            "name": "financeApiRequest",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestAccountProcessor.html#property_financeApiRequest"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor",
            "name": "InterestProcessor",
            "summary": "Functionality\u0020required\u0020for\u0020Interest\u0020Rates\u0020checks\u0020and\u0020handling",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003AselectRate\u0028\u0029",
            "name": "selectRate",
            "summary": "Select\u0020rate\u0020based\u0020on\u0020provided\u0020requirements\u0020which\u0020are\u0020in\u0020config",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#method_selectRate"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003AcalculateInterest\u0028\u0029",
            "name": "calculateInterest",
            "summary": "Calculate\u0020interest\u0020due",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#method_calculateInterest"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003AcompoundInterest\u0028\u0029",
            "name": "compoundInterest",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#method_compoundInterest"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003AcalculatePayoutCount\u0028\u0029",
            "name": "calculatePayoutCount",
            "summary": "Calculate\u0020how\u0020many\u0020days\u0020have\u0020passed\u0020since\u0020last\u0020payout",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#method_calculatePayoutCount"
        },                {
            "fqsen": "\\Finance\\IA\\Processor\\InterestProcessor\u003A\u003A\u0024interest_rates",
            "name": "interest_rates",
            "summary": "",
            "url": "classes/Finance-IA-Processor-InterestProcessor.html#property_interest_rates"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest",
            "name": "FinanceApiRequest",
            "summary": "API\u0020helper\u0020for\u0020the\u0020Finance\u0020Internet\u0020Account\u0020remote\u0020requests",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method___construct"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AsetUUID\u0028\u0029",
            "name": "setUUID",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_setUUID"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetUserStats\u0028\u0029",
            "name": "getUserStats",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getUserStats"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AsetUserStats\u0028\u0029",
            "name": "setUserStats",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_setUserStats"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AsetInterestRate\u0028\u0029",
            "name": "setInterestRate",
            "summary": "Set\u0020the\u0020interest\u0020rate\u0020through\u0020the\u0020API.\u0020The\u0020interest\u0020rate\u0020can\u0020only\u0020be\u0020set\u0020if\u0020there\u0020is\u0020no\u0020pre\u002Dassigned\u0020rate\u0020on\u0020the\u0020account.",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_setInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetInterestRate\u0028\u0029",
            "name": "getInterestRate",
            "summary": "Get\u0020the\u0020interest\u0020rate\u0020if\u0020it\u0020has\u0020already\u0020been\u0020assigned\u0020to\u0020the\u0020account.",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getInterestRate"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AdepositIntoAccount\u0028\u0029",
            "name": "depositIntoAccount",
            "summary": "Add\u0020funds\u0020to\u0020the\u0020account",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_depositIntoAccount"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetTotalBalance\u0028\u0029",
            "name": "getTotalBalance",
            "summary": "Get\u0020the\u0020total\u0020balance\u0020inside\u0020the\u0020user\u0027s\u0020account",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getTotalBalance"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AsetSkippedPayout\u0028\u0029",
            "name": "setSkippedPayout",
            "summary": "Send\u0020to\u0020the\u0020API\u0020the\u0020skipped\u0020payout\u0020so\u0020that\u0020it\u0020can\u0020be\u0020used\u0020and\u0020accumulated\u0020towards\u0020future\u0020payouts",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_setSkippedPayout"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetSkippedPayouts\u0028\u0029",
            "name": "getSkippedPayouts",
            "summary": "Get\u0020the\u0020total\u0020amount\u0020from\u0020previously\u0020skipped\u0020payouts",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getSkippedPayouts"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AresetSkippedPayouts\u0028\u0029",
            "name": "resetSkippedPayouts",
            "summary": "Clear\u0020the\u0020skipped\u0020payouts,\u0020this\u0020is\u0020for\u0020after\u0020the\u0020payout\u0020has\u0020been\u0020added\u0020to\u0020user\u0020balance",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_resetSkippedPayouts"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AstoreTransaction\u0028\u0029",
            "name": "storeTransaction",
            "summary": "Store\u0020a\u0020transaction\u0020record\u0020as\u0020a\u0020log\u0020that\u0020the\u0020process\u0020has\u0020been\u0020executed\u0020for\u0020the\u0020user",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_storeTransaction"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetLastPayout\u0028\u0029",
            "name": "getLastPayout",
            "summary": "Get\u0020the\u0020last\u0020datetime\u0020that\u0020a\u0020successful\u0020payout\u0020was\u0020done\u0020for\u0020the\u0020user",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getLastPayout"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetUserStatement\u0028\u0029",
            "name": "getUserStatement",
            "summary": "Get\u0020list\u0020of\u0020transactions\u0020as\u0020statement.\u0020Data\u0020in\u0020DESC\u0020order.",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getUserStatement"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AgetUserData\u0028\u0029",
            "name": "getUserData",
            "summary": "Get\u0020basic\u0020stats\u0020as\u0020provided\u0020by\u0020existing\u0020Finance\u0020API\u0020Contract",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#method_getUserData"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003AAPI_URL",
            "name": "API_URL",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#constant_API_URL"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003A\u0024userStats",
            "name": "userStats",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#property_userStats"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003A\u0024UUIDv4Object",
            "name": "UUIDv4Object",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#property_UUIDv4Object"
        },                {
            "fqsen": "\\Finance\\IA\\Request\\FinanceApiRequest\u003A\u003A\u0024guzzleClient",
            "name": "guzzleClient",
            "summary": "",
            "url": "classes/Finance-IA-Request-FinanceApiRequest.html#property_guzzleClient"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Finance\\IA",
            "name": "IA",
            "summary": "",
            "url": "namespaces/finance-ia.html"
        },                {
            "fqsen": "\\Finance",
            "name": "Finance",
            "summary": "",
            "url": "namespaces/finance.html"
        },                {
            "fqsen": "\\Finance\\IA\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/finance-ia-config.html"
        },                {
            "fqsen": "\\Finance\\IA\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/finance-ia-exception.html"
        },                {
            "fqsen": "\\Finance\\IA\\Object",
            "name": "Object",
            "summary": "",
            "url": "namespaces/finance-ia-object.html"
        },                {
            "fqsen": "\\Finance\\IA\\Processor",
            "name": "Processor",
            "summary": "",
            "url": "namespaces/finance-ia-processor.html"
        },                {
            "fqsen": "\\Finance\\IA\\Request",
            "name": "Request",
            "summary": "",
            "url": "namespaces/finance-ia-request.html"
        }            ]
);
